Dynamically generate headers

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -42,6 +42,7 @@ elif [[ "$OSTYPE" == "darwin"* ]]; then
     HOMEBREW_CACHE="/tmp" $BREWDIR/bin/brew install $PKG_BREW_NAME 2>&1 | sed 's/Warning/Note/g'
     rm -f $BREWDIR/opt/$PKG_BREW_NAME/lib/*.dylib
   fi
+  PROTOC_PATH="$BREWDIR/opt/$PKG_BREW_NAME/bin/"
   PKG_CFLAGS="-I$BREWDIR/opt/$PKG_BREW_NAME/include"
   PKG_LIBS="-L$BREWDIR/opt/$PKG_BREW_NAME/lib $PKG_LIBS"
 fi
@@ -76,6 +77,14 @@ fi
 
 # Write to Makevars
 sed -e "s|@cflags@|$PKG_CFLAGS|" -e "s|@libs@|$PKG_LIBS|" src/Makevars.in > src/Makevars
+
+# Compile protoc file
+cd src
+${PROTOC_PATH}protoc rexp.proto --cpp_out=.
+if [ $? -ne 0 ]; then
+  echo "Error: failed to compile rexp.proto file. Please install protobuf-compiler for your system."
+  exit 1
+fi
 
 # Success
 exit 0
